libs =
import libs += doctest%lib{doctest}
import libs += libasio%lib{asio}
import libs += spdlog%lib{spdlog}
import libs += libboost-uuid%lib{boost_uuid}

include ../raftlib/
exe{tests}: {hxx ixx txx cxx}{**} $libs ../raftlib/lib{raft}

cxx.poptions =+ "-I$out_root" "-I$src_root"
cxx.coptions=-O3 -Wall -Wpedantic -Werror
