libs =
import libs += libasio%lib{asio}
import libs += libboost-program-options%lib{boost_program_options}
import libs += spdlog%lib{spdlog}
import libs += yaml-cpp%lib{yaml-cpp}
import libs += libboost-uuid%lib{boost_uuid}
import libs += libboost-serialization%lib{boost_serialization}

lib{raft}: {hxx ixx txx cxx}{**} $libs

cxx.poptions =+ "-I$out_root" "-I$src_root"
cxx.coptions=-O3
