libs =
import libs += libasio%lib{asio}
import libs += libboost-program-options%lib{boost_program_options}
import libs += spdlog%lib{spdlog}

include ../raftlib/
exe{raft}: {hxx ixx txx cxx}{**} $libs ../raftlib/lib{raft}

cxx.poptions =+ "-I$out_root" "-I$src_root"
cxx.coptions=-O3
