libs =
import libs += libasio%lib{asio}
import libs += yaml-cpp%lib{yaml-cpp}
import libs += spdlog%lib{spdlog}
import libs += libboost-uuid%lib{boost_uuid}
import libs += libboost-lexical-cast%lib{boost_lexical_cast}

include ../raftlib/
exe{raft}: {hxx ixx txx cxx}{**} $libs ../raftlib/lib{raft}

cxx.poptions =+ "-I$out_root" "-I$src_root"
cxx.coptions=-O3
